import base64
import binascii
from typing import Generator

class CellularAutomataCipher:
    """
    A class to perform Stream Cipher operations using an Elementary Cellular Automaton.

    Disclaimer: While Rule 30 is a complex PRNG, elementary cellular automata
    are generally not considered cryptographically secure for modern
    defense-in-depth implementations and are utilized here as an advanced
    cryptographic primitive for educational and architectural demonstration.

    This class provides methods to initialize CA state, apply rules, generate
    a keystream, and perform encryption/decryption.
    """

    def __init__(self) -> None:
        """
        Initializes the CellularAutomataCipher with empty state.
        """
        self.state: list[int] = []
        self.rule_map: dict[tuple[int, int, int], int] = {}

    @classmethod
    def validate_parameters(
        cls, key: str, rule: int = 30
    ) -> tuple[list[int], dict[tuple[int, int, int], int]]:
        """
        Validates the key and rule parameters and prepares the CA state.

        Args:
            key (str): The encryption key used to seed the initial state.
            rule (int): The elementary CA rule number (0-255). Defaults to 30.

        Returns:
            tuple[list[int], dict[tuple[int, int, int], int]]: The initial bit
                state and the rule lookup dictionary.

        Raises:
            ValueError: If the key is empty or rule is out of range.
        """
        if not key:
            raise ValueError("Key cannot be empty.")
        if not (0 <= rule <= 255):
            raise ValueError("Rule must be between 0 and 255.")

        # Convert key to bits
        key_bytes = key.encode("utf-8")
        state = []
        for byte in key_bytes:
            for i in range(7, -1, -1):
                state.append((byte >> i) & 1)

        # Prevent CA lockup if all bits are 0
        if sum(state) == 0:
            center_idx = len(state) // 2
            state[center_idx] = 1

        # Generate rule lookup dictionary
        rule_bin = format(rule, "08b")
        rule_map = {}
        for i in range(8):
            # i represents the neighborhood (Left, Center, Right) as an integer
            neighborhood = (i >> 2 & 1, i >> 1 & 1, i & 1)
            # The rule bit at index 'i' corresponds to the result for neighborhood 'i'
            rule_map[neighborhood] = int(rule_bin[7 - i])

        return state, rule_map

    def _step(self) -> int:
        """
        Simulates one generation of the automaton using periodic boundary conditions.

        Updates the internal state array and returns the center bit.

        Returns:
            int: The center bit of the new state array.
        """
        new_state = []
        n = len(self.state)

        for i in range(n):
            # Periodic boundary conditions
            left = self.state[(i - 1) % n]
            center = self.state[i]
            right = self.state[(i + 1) % n]
            
            new_state.append(self.rule_map[(left, center, right)])

        self.state = new_state
        return self.state[n // 2]

    def _generate_byte_stream(self) -> Generator[int, None, None]:
        """
        Yields an infinite sequence of bytes generated from the CA.

        Each byte is formed by calling _step() 8 consecutive times.

        Yields:
            int: An 8-bit integer keystream byte.
        """
        while True:
            byte = 0
            for _ in range(8):
                bit = self._step()
                byte = (byte << 1) | bit
            yield byte

    def encrypt(self, plaintext: str, key: str, rule: int = 30) -> str:
        """
        Encrypts plaintext using a CA-generated byte stream.

        Args:
            plaintext (str): The text to be encrypted.
            key (str): The encryption key.
            rule (int): The CA rule number.

        Returns:
            str: Base64 encoded ciphertext string.

        Raises:
            ValueError: If parameters are invalid.
        """
        if not plaintext:
            return ""

        self.state, self.rule_map = self.validate_parameters(key, rule)
        plaintext_bytes = plaintext.encode("utf-8")
        
        keystream = self._generate_byte_stream()
        ciphertext_bytes = bytearray()
        
        for p_byte in plaintext_bytes:
            ciphertext_bytes.append(p_byte ^ next(keystream))
            
        return base64.b64encode(ciphertext_bytes).decode("utf-8")

    def decrypt(self, ciphertext: str, key: str, rule: int = 30) -> str:
        """
        Decrypts Base64 encoded ciphertext using a CA-generated byte stream.

        Args:
            ciphertext (str): The Base64 encoded ciphertext.
            key (str): The decryption key.
            rule (int): The CA rule number.

        Returns:
            str: Decrypted plaintext string.

        Raises:
            ValueError: If parameters are invalid or ciphertext is corrupted.
        """
        if not ciphertext:
            return ""

        self.state, self.rule_map = self.validate_parameters(key, rule)
        
        try:
            ciphertext_bytes = base64.b64decode(ciphertext.encode("utf-8"), validate=True)
        except (binascii.Error, ValueError) as e:
            raise ValueError("Corrupted ciphertext: invalid Base64 payload.") from e
            
        keystream = self._generate_byte_stream()
        plaintext_bytes = bytearray()
        
        for c_byte in ciphertext_bytes:
            plaintext_bytes.append(c_byte ^ next(keystream))
            
        return plaintext_bytes.decode("utf-8", errors="replace")
