import base64
import binascii
from typing import Generator

class LFSRCipher:
    """
    A class to perform Stream Cipher operations using a Linear Feedback Shift Register (LFSR).

    Disclaimer: A standalone LFSR is vulnerable to known-plaintext attacks
    (e.g., Berlekamp-Massey algorithm) and is implemented here as a
    foundational cryptographic primitive for educational and architectural
    demonstration.

    This class provides methods to initialize state, step the register,
    generate a byte stream, and perform encryption/decryption.
    """

    def __init__(self) -> None:
        """
        Initializes the LFSRCipher with an empty state.
        """
        self.state: list[int] = []
        self.taps: list[int] = []

    @classmethod
    def validate_parameters(cls, seed: str, taps: list[int]) -> tuple[list[int], list[int]]:
        """
        Validates the initial state (seed) and tap positions.

        Args:
            seed (str): A binary string of '0's and '1's representing the initial state.
            taps (list[int]): Indices of the bits to be used for feedback.

        Returns:
            tuple[list[int], list[int]]: A tuple containing the seed as a list
                of integers and the validated taps.

        Raises:
            ValueError: If the seed is empty, contains non-binary characters,
                is entirely zeros, or if taps are out of range.
        """
        if not seed:
            raise ValueError("Seed cannot be empty.")
        
        if not all(c in '01' for c in seed):
            raise ValueError("Seed must contain only '0's and '1's.")
            
        seed_list = [int(c) for c in seed]
        if sum(seed_list) == 0:
            raise ValueError("Seed cannot be entirely zeros (LFSR lock-up).")
            
        seed_len = len(seed_list)
        for tap in taps:
            if not (0 <= tap < seed_len):
                raise ValueError(f"Tap index {tap} is out of range for seed length {seed_len}.")
                
        return seed_list, taps

    def _step(self) -> int:
        """
        Simulates one clock cycle of the shift register.

        Calculates the feedback bit by XORing bits at tap indices, shifts
        the state right, and inserts the feedback bit at the leftmost position.

        Returns:
            int: The bit that was shifted out (the rightmost bit).
        """
        feedback = 0
        for tap in self.taps:
            feedback ^= self.state[tap]
            
        shifted_out_bit = self.state.pop()
        self.state.insert(0, feedback)
        
        return shifted_out_bit

    def _generate_byte_stream(self) -> Generator[int, None, None]:
        """
        Yields an infinite sequence of bytes (0-255) generated from the LFSR.

        Each byte is formed by accumulating 8 consecutive bits from the LFSR.

        Yields:
            int: An 8-bit integer keystream byte.
        """
        while True:
            byte = 0
            for _ in range(8):
                bit = self._step()
                byte = (byte << 1) | bit
            yield byte

    def encrypt(self, plaintext: str, seed: str, taps: list[int]) -> str:
        """
        Encrypts plaintext using an LFSR-generated byte stream.

        Args:
            plaintext (str): The text to be encrypted.
            seed (str): The initial state binary string.
            taps (list[int]): The feedback tap indices.

        Returns:
            str: Base64 encoded ciphertext string.

        Raises:
            ValueError: If the parameters are invalid.
        """
        if not plaintext:
            return ""

        self.state, self.taps = self.validate_parameters(seed, taps)
        plaintext_bytes = plaintext.encode("utf-8")
        
        keystream = self._generate_byte_stream()
        ciphertext_bytes = bytearray()
        
        for p_byte in plaintext_bytes:
            ciphertext_bytes.append(p_byte ^ next(keystream))
            
        return base64.b64encode(ciphertext_bytes).decode("utf-8")

    def decrypt(self, ciphertext: str, seed: str, taps: list[int]) -> str:
        """
        Decrypts Base64 encoded ciphertext using an LFSR-generated byte stream.

        Args:
            ciphertext (str): The Base64 encoded ciphertext.
            seed (str): The initial state binary string.
            taps (list[int]): The feedback tap indices.

        Returns:
            str: Decrypted plaintext string.

        Raises:
            ValueError: If parameters are invalid or ciphertext is corrupted.
        """
        if not ciphertext:
            return ""

        self.state, self.taps = self.validate_parameters(seed, taps)
        
        try:
            ciphertext_bytes = base64.b64decode(ciphertext.encode("utf-8"), validate=True)
        except (binascii.Error, ValueError) as e:
            raise ValueError("Corrupted ciphertext: invalid Base64 payload.") from e
            
        keystream = self._generate_byte_stream()
        plaintext_bytes = bytearray()
        
        for c_byte in ciphertext_bytes:
            plaintext_bytes.append(c_byte ^ next(keystream))
            
        return plaintext_bytes.decode("utf-8", errors="replace")
