import base64
import binascii
from typing import Generator, List, Tuple

class NLFSRCipher:
    """
    A class to perform Stream Cipher operations using a Nonlinear Feedback Shift Register (NLFSR).

    Disclaimer: Designing a secure NLFSR requires mathematically guaranteeing a
    maximal period (e.g., creating de Bruijn sequences), and this implementation
    serves as an advanced cryptographic primitive for educational and
    architectural demonstration.

    This class provides methods to initialize state, perform non-linear stepping,
    generate a keystream, and perform encryption/decryption.
    """

    def __init__(self) -> None:
        """
        Initializes the NLFSRCipher with an empty state.
        """
        self.state: List[int] = []
        self.anf_terms: List[Tuple[int, ...]] = []

    @classmethod
    def validate_parameters(
        cls, seed: str, anf_terms: List[Tuple[int, ...]]
    ) -> Tuple[List[int], List[Tuple[int, ...]]]:
        """
        Validates the initial state (seed) and Algebraic Normal Form (ANF) terms.

        Args:
            seed (str): A binary string representing the initial state.
            anf_terms (List[Tuple[int, ...]]): A list of tuples where each tuple
                represents a conjunction (AND) of bits at those indices.

        Returns:
            Tuple[List[int], List[Tuple[int, ...]]]: Validated seed as bit list
                and the ANF terms.

        Raises:
            ValueError: If the seed is empty, contains non-binary characters,
                or if ANF term indices are out of range.
        """
        if not seed:
            raise ValueError("Seed cannot be empty.")
        if not all(c in "01" for c in seed):
            raise ValueError("Seed must contain only '0's and '1's.")

        seed_list = [int(c) for c in seed]
        seed_len = len(seed_list)

        for term in anf_terms:
            for index in term:
                if not (0 <= index < seed_len):
                    raise ValueError(
                        f"Index {index} in anf_terms is out of range for seed length {seed_len}."
                    )

        return seed_list, anf_terms

    def _step(self) -> int:
        """
        Simulates one clock cycle of the nonlinear feedback shift register.

        Calculates the feedback bit by XORing the results of AND operations
        defined in anf_terms.

        Returns:
            int: The bit shifted out from the rightmost position.
        """
        feedback = 0
        for term in self.anf_terms:
            term_result = 1
            for index in term:
                term_result &= self.state[index]
            feedback ^= term_result

        shifted_out_bit = self.state.pop()
        self.state.insert(0, feedback)
        return shifted_out_bit

    def _generate_byte_stream(self) -> Generator[int, None, None]:
        """
        Yields an infinite sequence of bytes generated from the NLFSR.

        Each byte is formed by accumulating 8 consecutive output bits.

        Yields:
            int: An 8-bit integer keystream byte.
        """
        while True:
            byte = 0
            for _ in range(8):
                bit = self._step()
                byte = (byte << 1) | bit
            yield byte

    def encrypt(self, plaintext: str, seed: str, anf_terms: List[Tuple[int, ...]]) -> str:
        """
        Encrypts plaintext using an NLFSR-generated byte stream.

        Args:
            plaintext (str): The text to be encrypted.
            seed (str): The initial state binary string.
            anf_terms (List[Tuple[int, ...]]): The nonlinear feedback terms.

        Returns:
            str: Base64 encoded ciphertext string.

        Raises:
            ValueError: If parameters are invalid.
        """
        if not plaintext:
            return ""

        self.state, self.anf_terms = self.validate_parameters(seed, anf_terms)
        plaintext_bytes = plaintext.encode("utf-8")
        
        keystream = self._generate_byte_stream()
        ciphertext_bytes = bytearray()
        
        for p_byte in plaintext_bytes:
            ciphertext_bytes.append(p_byte ^ next(keystream))
            
        return base64.b64encode(ciphertext_bytes).decode("utf-8")

    def decrypt(self, ciphertext: str, seed: str, anf_terms: List[Tuple[int, ...]]) -> str:
        """
        Decrypts Base64 encoded ciphertext using an NLFSR-generated byte stream.

        Args:
            ciphertext (str): The Base64 encoded ciphertext.
            seed (str): The initial state binary string.
            anf_terms (List[Tuple[int, ...]]): The nonlinear feedback terms.

        Returns:
            str: Decrypted plaintext string.

        Raises:
            ValueError: If parameters are invalid or ciphertext is corrupted.
        """
        if not ciphertext:
            return ""

        self.state, self.anf_terms = self.validate_parameters(seed, anf_terms)
        
        try:
            ciphertext_bytes = base64.b64decode(ciphertext.encode("utf-8"), validate=True)
        except (binascii.Error, ValueError) as e:
            raise ValueError("Corrupted ciphertext: invalid Base64 payload.") from e
            
        keystream = self._generate_byte_stream()
        plaintext_bytes = bytearray()
        
        for c_byte in ciphertext_bytes:
            plaintext_bytes.append(c_byte ^ next(keystream))
            
        return plaintext_bytes.decode("utf-8", errors="replace")
